---
sudo: required
language: python
services: docker

install:
  - pip install molecule
  - pip install docker

script:
  - molecule --debug test

after_failure:
  # Check what happened on systemd systems.
  - 'docker exec --tty fedora27 env TERM=xterm systemctl --no-pager -l status php-fpm.service'
  - 'docker exec --tty fedora28 env TERM=xterm systemctl --no-pager -l status php-fpm.service'
  - 'docker exec --tty fedora27 env TERM=xterm journalctl -xe --no-pager'
  - 'docker exec --tty fedora28 env TERM=xterm journalctl -xe --no-pager'
