---
sudo: required
language: python
services:
  - docker
cache:
  - pip
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -o Dpkg::Options::='--force-confold' --force-yes -y docker-ce
install:
  - pip install molecule
  - pip install docker
  - molecule create
  - molecule destroy
script:
  - molecule --debug test
