---
sudo: required
language: python
services:
  - docker
cache:
  - pip
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install tree
install:
  - pip install molecule
  - pip install docker
script:
  - molecule --debug test
after_failure:
  - ls -l /tmp
  - tree /tmp/molecule
