---
sudo: required
language: python
services:
  - docker
cache:
  - pip
before_install:
  - sudo apt-get -qq update
install:
  - virtualenv --no-site-packages .venv
  - source .venv/bin/activate
  - pip install ansible==2.5.0
  - pip install -r install.txt
script:
  - source .venv/bin/activate
  - molecule test
