---
# tasks file for common/fedora
- name: Install RPM Fusion (free)
  dnf:
    name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
    state: present
- name: Install RPM Fusion (nonfree)
  dnf:
    name: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
    state: present
- name: Install simple programs
  dnf: name={{ item }} state=present
  with_items:
  - '@Development Tools'
  - ansible
  - bzr
  - cloc
  - filezilla
  - gcc-c++
  - gnome-terminal-nautilus
  - gnome-tweak-tool
  - htop
  - libselinux-python
  - mycli
  - nano
  - python2-mysql
  - redhat-rpm-config
  - ruby
  - ruby-devel
  - sqlite
  - sqlite-devel
  - terminator
  - vagrant
  - vim
  - vim-powerline
  - vlc
  - zsh
- name: Disable selinux
  selinux: state=disabled
- name: Install and configure mariadb
  block:
    - dnf: name={{ item }} state=present
      with_items:
        - mariadb
        - mariadb-server
    - systemd: name=mariadb enabled=true state=started
- name: Set mariadb root password
  mysql_user: name=root password={{ mysql_root_password }} login_password={{ mysql_old_root_password }}
  when: mysql_root_password != mysql_old_root_password
  ignore_errors: true
- name: Create ~/.my.cnf
  template:
    src: templates/mariadb/.my.cnf.j2
    dest: "/home/{{ primary_user }}/.my.cnf"
    owner: "{{ primary_user }}"
    group: "{{ primary_group }}"
- name: Install redis
  block:
    - dnf: name=redis state=present
    - systemd: name=redis enabled=true state=started
- name: Install mailcatcher
  gem: name=mailcatcher state=present
- name: Create mailcatcher service
  template: src=templates/mailcatcher/mailcatcher.service.j2 dest=/usr/lib/systemd/system/mailcatcher.service
  notify:
    - systemd
- name: Run mailcatcher service
  systemd: name=mailcatcher enabled=true state=started
# Remi's RPM repository
# https://rpms.remirepo.net
#
# Command to install:
#    dnf --enablerepo=remi install php70
# Command to install additional packages:
#    dnf --enablerepo=remi install php70-php-xxx
- name: Install Remi's RPM repository
  dnf:
    name: http://rpms.remirepo.net/fedora/remi-release-{{ ansible_distribution_version }}.rpm
    state: present
- name: Install and configure php
  block:
    - dnf: name={{ item }} state=present
      with_items:
        - composer
        - php
        - php-bcmath
        - php-fpm
        - php-gd
        - php-intl
        - php-json
        - php-mbstring
        - php-mcrypt
        - php-opcache
        - php-pdo
        - php-soap
        - php-xdebug
        - php-xml
        - php-zip
      notify:
        - php-fpm
    - template: src=templates/php/99-local.ini.j2 dest=/etc/php.d/99-local.ini
      notify:
        - php-fpm
    - template: src=templates/php/local.www.conf.j2 dest=/etc/php-fpm.d/local.www.conf
      notify:
        - php-fpm
    - systemd: name=php-fpm enabled=true state=started
# TODO: Install nginx_config_reloader.
- name: Install and configure nginx
  block:
    - dnf: name=nginx state=present
      notify:
        - nginx
    - template: src=templates/nginx/nginx.conf.j2 dest=/etc/nginx/nginx.conf
      notify:
        - nginx
    - template: src=templates/nginx/default.conf.j2 dest=/etc/nginx/default.conf
      notify:
        - nginx
    - template: src=templates/nginx/magento2.conf.j2 dest=/etc/nginx/magento2.conf
      notify:
        - nginx
    - template: src=templates/nginx/php-fpm.conf.j2 dest=/etc/nginx/conf.d/php-fpm.conf
      notify:
        - nginx
    - template: src=templates/nginx/mailcatcher.conf.j2 dest=/etc/nginx/conf.d/mailcatcher.conf
      notify:
        - nginx
    - systemd: name=nginx enabled=true state=started
- name: Install Google Chrome
  dnf:
    name: https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
    state: present
  when: install_chrome
- name: Install Nvidia drivers
  dnf: name={{ item }} state=present
  with_items:
    - xorg-x11-drv-nvidia
    - akmod-nvidia
  when: install_nvidia_drivers
- name: Install Steam
  dnf: name=steam state=present
  when: install_steam
- name: Install Owncloud
  dnf: name={{ item }} state=present
  with_items:
    - owncloud-client
    - owncloud-client-nautilus
  when: install_owncloud_client
- name: Download Atom rpm
  get_url: url=https://atom.io/download/rpm dest=/tmp/atom.rpm
  when: install_atom
- name: Install Atom
  dnf: name=/tmp/atom.rpm state=latest
  when: install_atom
- name: Install Spotify repository
  get_url: url=https://negativo17.org/repos/fedora-spotify dest=/etc/yum.repos.d/fedora-spotify.repo
  when: install_spotify
- name: Install Spotify
  dnf: name=spotify state=present
  when: install_spotify
- name: Disable ipv6
  template: src=templates/sysctl/99-ipv6.conf dest=/etc/sysctl.d/99-ipv6.conf
  notify:
    - sysctl
  when: disable_ipv6
- name: Install oh-my-zsh
  block:
    - name: Clone oh-my-zsh
      git:
        repo: https://github.com/robbyrussell/oh-my-zsh.git
        dest: "/home/{{ primary_user }}/.oh-my-zsh"
        clone: true
        update: true
      tags:
        - zsh
    - name: Register .zshrc existence
      stat: path="/home/{{ primary_user }}/.zshrc"
      register: zshrc_file
    - name: Copy .zshrc
      copy:
        src: "/home/{{ primary_user }}/.oh-my-zsh/templates/zshrc.zsh-template"
        dest: "/home/{{ primary_user }}/.zshrc"
        remote_src: true
      when: not zshrc_file.stat.exists
    - name: Init shell
      user:
        name: "{{ primary_user }}"
        shell: /bin/zsh
  become: true
  become_user: "{{ primary_user }}"
