---
# tasks file for common
- name: Install dnf-plugins-core
  dnf:
    name: dnf-plugins-core
    state: present
- name: Install Remi's RPM repository
  dnf:
    name: http://rpms.remirepo.net/fedora/remi-release-{{ ansible_distribution_version }}.rpm
    state: present
  tags: php
- name: Enable Remi's RPM repository
  command: "dnf config-manager --set-enabled remi"
  changed_when: false
  tags: php

- name: Remove php70
  dnf:
    name: "{{ item }}"
    state: absent
  with_items:
    - php70-php
    - php70-php-apcu
    - php70-php-bcmath
    - php70-php-fpm
    - php70-php-gd
    - php70-php-imagick
    - php70-php-intl
    - php70-php-json
    - php70-php-mbstring
    - php70-php-mcrypt
    - php70-php-mysqlnd
    - php70-php-opcache
    - php70-php-pdo
    - php70-php-soap
    - php70-php-xdebug
    - php70-php-xml
    - php70-php-zip
  notify: php70
  tags: php

- name: Install php71
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - php71-php
    - php71-php-apcu
    - php71-php-bcmath
    - php71-php-fpm
    - php71-php-gd
    - php71-php-imagick
    - php71-php-intl
    - php71-php-json
    - php71-php-mbstring
    - php71-php-mcrypt
    - php71-php-mysqlnd
    - php71-php-opcache
    - php71-php-pdo
    - php71-php-soap
    - php71-php-xdebug
    - php71-php-xml
    - php71-php-zip
  notify: php71
  tags: php

- name: Install php72
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - php72-php
    - php72-php-apcu
    - php72-php-bcmath
    - php72-php-fpm
    - php72-php-gd
    - php72-php-imagick
    - php72-php-intl
    - php72-php-json
    - php72-php-mbstring
    - php72-php-mcrypt
    - php72-php-mysqlnd
    - php72-php-opcache
    - php72-php-pdo
    - php72-php-soap
    - php72-php-xdebug
    - php72-php-xml
    - php72-php-zip
  notify: php72
  tags: php

# - name: Run Fedora flavor
#   include_tasks: fedora.yml
#   when: ansible_distribution == "Fedora"
# - name: Run MacOS flavor
#   include_tasks: macos.yml
#   when: ansible_distribution == "MacOSX"
