---
# handlers file for common
- name: php-fpm
  systemd: name=php-fpm state=restarted
- name: nginx
  systemd: name=nginx state=restarted
- name: systemd
  systemd: daemon_reload=true
- name: sysctl
  command: sysctl -p
- name: nginx-config-reloader
  systemd: name=nginx-config-reloader state=restarted
